force-app/main/default/objects/PED_Blacklist_Domini_Email__c/PED_Blacklist_Domini_Email__c.object-meta.xml
<CustomObject>
    <label>Blacklist Domini Email</label>
    <nameField>
        <displayFormat>BLIST-{0000000000}</displayFormat>
        <label>Blacklist Domini Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blacklist Domini Email</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PED_Blacklisted_Email__c/PED_Blacklisted_Email__c.object-meta.xml
<CustomObject>
    <label>PED_Blacklisted_Email</label>
    <nameField>
        <displayFormat>BKL-{00000000}</displayFormat>
        <label>PED_Blacklisted_Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PED_Blacklisted_Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PED_Blacklisted_Email__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>contiene l&apos;indirizzo email o parte di esso in considerato in blacklist</description>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PED_Blacklisted_Email__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Per blacklist fisso sull&apos;indirizzo intero</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/PED_Blacklisted_Email__c/recordTypes/WildCard.recordType-meta.xml
<RecordType>
    <fullName>WildCard</fullName>
    <active>true</active>
    <description>Per blacklist sulle wildcard</description>
    <label>WildCard</label>
</RecordType>

force-app/main/default/classes/PED_CheckBlacklistedEmail.cls
public without sharing class PED_CheckBlacklistedEmail {
    @AuraEnabled
    public static Boolean checkBlacklistedEmail(String email){
    	String dominio = email.substringAfter('@');
    	List<PED_Blacklist_Domini_Email__c> checkDomain = [SELECT Id FROM PED_Blacklist_Domini_Email__c WHERE Name =: dominio];
		if(!checkDomain.isEmpty())
			return true;
		else
			return false;
	}
    
    @AuraEnabled
    public static void flagDisposable(Contact c){
		c.PED_Email_Disposable__c = true;
        update c;        
	}
	
	@AuraEnabled
	public static Boolean checkBlacklistedSpecifiedEmail(String email){
    	String blackEmail = email.substringBefore('@') + '%';
    	String query = 'SELECT Id, Email__c FROM PED_Blacklisted_Email__c WHERE RecordType.Name = \'WildCard\' LIMIT 10000';
    	List<String> listEmailBl = new List<String>();
		Database.QueryLocator q = Database.getQueryLocator(query);
		Database.QueryLocatorIterator it =  q.iterator();
		while (it.hasNext()){
		    PED_Blacklisted_Email__c bklEmailDB = (PED_Blacklisted_Email__c)it.next();
		    if(blackEmail.contains(bklEmailDB.email__c))
		    	return true;
		}
		
		List<PED_Blacklisted_Email__c> checkDomain = [SELECT Id FROM PED_Blacklisted_Email__c WHERE Email__c =: email AND RecordType.Name = 'Standard' LIMIT 1];
		if(!checkDomain.isEmpty())
			return true;
		else
			return false;
	}
}