force-app/main/default/objects/PED_Blacklist_Domini_Email__c/PED_Blacklist_Domini_Email__c.object-meta.xml
<CustomObject>
    <label>Blacklist Domini Email</label>
    <nameField>
        <displayFormat>BLIST-{0000000000}</displayFormat>
        <label>Blacklist Domini Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blacklist Domini Email</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PED_Blacklisted_Email__c/PED_Blacklisted_Email__c.object-meta.xml
<CustomObject>
    <label>PED_Blacklisted_Email</label>
    <nameField>
        <displayFormat>BKL-{00000000}</displayFormat>
        <label>PED_Blacklisted_Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PED_Blacklisted_Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PED_Blacklisted_Email__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>contiene l&apos;indirizzo email o parte di esso in considerato in blacklist</description>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PED_Blacklisted_Email__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Per blacklist fisso sull&apos;indirizzo intero</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/PED_Blacklisted_Email__c/recordTypes/WildCard.recordType-meta.xml
<RecordType>
    <fullName>WildCard</fullName>
    <active>true</active>
    <description>Per blacklist sulle wildcard</description>
    <label>WildCard</label>
</RecordType>

force-app/main/default/classes/PED_CheckBlacklistedEmail_Test.cls
@isTest
private class PED_CheckBlacklistedEmail_Test {
    static testMethod void method1() {
        PED_Blacklisted_Email__c pbl = new PED_Blacklisted_Email__c();
        RecordType rt = [SELECT Id FROM RecordType WHERE RecordType.DeveloperName = 'WildCard' LIMIT 1];
        pbl.RecordTypeId = rt.Id;
        pbl.Email__c = 'merope';
        insert pbl; 
        
        PED_Blacklisted_Email__c pbl2 = new PED_Blacklisted_Email__c();
        RecordType rt2 = [SELECT Id FROM RecordType WHERE RecordType.DeveloperName = 'Standard' LIMIT 1];
        pbl2.RecordTypeId = rt2.Id;
        pbl2.Email__c = 'iygasdfas@asddgsfg.df';
        insert pbl2;
        
        PED_Blacklist_Domini_Email__c bd = new PED_Blacklist_Domini_Email__c();
        bd.Name = 'pippo.com';
        insert bd;

        Contact contact = new Contact();
        contact.FirstName = 'Aditya';
        contact.LastName = 'Gupta';
        contact.Codice_Fiscale__c = 'GPTDTY80A01H501V';
        insert contact;
        
        PED_CheckBlacklistedEmail.checkBlacklistedSpecifiedEmail('iygasdfas@asddgsfg.df');
        PED_CheckBlacklistedEmail.checkBlacklistedSpecifiedEmail('merope@gmail.com');
        PED_CheckBlacklistedEmail.checkBlacklistedEmail('merope@pippo.com');
        PED_CheckBlacklistedEmail.flagDisposable(contact);
    }
}